### ISSUE TITLE
Add Uninstall-Target to match the Install-Target

### ISSUE THREAD

**Issue by BLuedtke** [uniba-swt/libbidib#19]
The recently added install target (see [PR](https://github.com/uniba-swt/libbidib/pull/12)) works. There is no way to automatically uninstall what can be installed though, which is inconvenient. I'll work on adding an appropriate uninstall option via cmake/make.

**Comment by eyip002** [comment]
https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake
