### ISSUE TITLE
Documentation for Physical Tests

### ISSUE THREAD

**Issue by eyip002** [uniba-swt/libbidib#3]
The `libbidib/test/physical-test/Readme.md` file is incomplete:

- [x] Under the main heading, add a brief description of the purpose and capabilities of the test suite
- [x] Mention any restrictions on the possible SWTbahn platforms
- [x] Mention any limitations of the test cases
- [x] Add a brief description to each test case
- [x] Elaborate on the dependencies
- [x] Elaborate on the build procedure
- [x] Mention how to stop a test case
- [x] Elaborate on the importance of the list of points and signals

**Comment by eyip002** [comment]
@clehanka What are the main limitations of each test case?

**Comment by clehanka** [comment]
I also need to document the basic usage of the functions and stuctures of the test-suite
