### ISSUE TITLE
Complete the Track Coverage of the Physical Test

### ISSUE THREAD

**Issue by eyip002** [uniba-swt/libbidib#4]
The track coverage test case of libbidib/test/physical-test is incomplete for the SWTbahn Standard platform. For example, point 7 is only tested in the normal position.

- [ ] Points are driven through in all positions and in all directions

**Comment by clehanka** [comment]
oh ok I will change it and write then Benjamin to test it.

**Comment by BLuedtke** [comment]
A little stale, but I found something.
Point 9 is in an incorrect aspect at one point of the test for SWTbahn-Standard. On line 293 of [swtbahn-standard/testsuite.c](https://github.com/uniba-swt/libbidib/blob/master/test/physical/swtbahn-standard/testsuite.c), it should not set point 9 to normal, as the route from seg40 to seg28 requires it to be in reverse orientation. This can be validated by looking at the routing table at https://github.com/uniba-swt/swtbahn-cli/blob/master/configurations/swtbahn-standard/interlocking_table.yml, route 187. Point 9 is in reverse there, and this route corresponds to the path being driven in this test.

Point 9 should be set to straight on line 301 instead.

**Comment by eyip002** [comment]
Fixed the physical test for SWTbahn Standard in [c6979eb](https://github.com/uniba-swt/libbidib/commit/c6979eba1d75424cb4040dba50d07d01f7f13461)
